# Generated by Django 4.1.3 on 2022-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_pro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='code_json',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topics',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
