# Generated by Django 4.1.3 on 2022-11-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_pro_app', '0002_topics_code_json_topics_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='code_json',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py_pro_app.topics')),
            ],
        ),
    ]
