# Generated by Django 4.1.3 on 2022-11-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_pro_app', '0003_remove_topics_code_json_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-added',)},
        ),
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='deficult_level',
            field=models.CharField(choices=[('Easy', 'easy'), ('Medium', 'medium'), ('Hard', 'hard')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='describ',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
