# Generated by Django 4.1.3 on 2022-11-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_pro_app', '0005_alter_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py_pro_app.topics'),
        ),
    ]
